=== skoba/mml/schema/draft/firstclinic.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- *************************************************** -->
<!-- 初診時特有情報 -->
<!-- FirstClinicModule XSD Version 4.0 -->
<!-- *************************************************** -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.medxml.net/MML/v4/ContentModule/FirstClinic/1.0" 
  xmlns:mmlFcl="http://www.medxml.net/MML/v4/ContentModule/FirstClinic/1.0"
  xmlns:mmlRd="http://www.medxml.net/MML/v4/ContentModule/RegisteredDiagnosis/1.0"
  xmlns:mmlFc="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
  >
  
  <xs:import namespace="http://www.medxml.net/MML/v4/ContentModule/RegisteredDiagnosis/1.0" schemaLocation="registereddiagnosis.xsd" />
  <xs:import namespace="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0" schemaLocation="facility.xsd" />
  
  <xs:element name="FirstClinicModule">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="mmlFcl:familyHistory"/>
        <xs:element minOccurs="0" ref="mmlFcl:childhood"/>
        <xs:element minOccurs="0" ref="mmlFcl:pastHistory"/>
        <xs:element minOccurs="0" ref="mmlFcl:chiefComplaints"/>
        <xs:element minOccurs="0" ref="mmlFcl:presentIllnessNotes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="familyHistory">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="mmlFcl:familyHistoryItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="familyHistoryItem" >
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mmlFcl:relation"/>
        <xs:element ref="mmlRd:RegisteredDiagnosisModule"/>
        <xs:element ref="mmlFcl:age" minOccurs="0"/>
        <xs:element ref="mmlFcl:memo" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="relation" type="xs:string"/>
  
  <xs:element name="age" type="xs:string"/>
  
  <xs:element name="memo" type="xs:string"/>
  
  <xs:element name="childhood">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="mmlFcl:birthInfo"/>
        <xs:element minOccurs="0" ref="mmlFcl:vaccination"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="birthInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="mmlFc:Facility"/>
        <xs:element minOccurs="0" ref="mmlFcl:deliveryWeeks"/>
        <xs:element minOccurs="0" ref="mmlFcl:deliveryMethod"/>
        <xs:element minOccurs="0" ref="mmlFcl:bodyWeight"/>
        <xs:element minOccurs="0" ref="mmlFcl:bodyHeight"/>
        <xs:element minOccurs="0" ref="mmlFcl:chestCircumference"/>
        <xs:element minOccurs="0" ref="mmlFcl:headCircumference"/>
        <xs:element minOccurs="0" ref="mmlFcl:memo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="deliveryWeeks" type="xs:string"/>
  
  <xs:element name="deliveryMethod" type="xs:string"/>
  
  <xs:element name="bodyWeight">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="mmlFcl:attlist.bodyWeight"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.bodyWeight">
    <xs:attribute name="unit" use="required" form="qualified"/>
  </xs:attributeGroup>
  
  <xs:element name="bodyHeight">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="mmlFcl:attlist.bodyHeight"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.bodyHeight">
    <xs:attribute name="unit" use="required" form="qualified"/>
  </xs:attributeGroup>
  
  <xs:element name="chestCircumference">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="mmlFcl:attlist.chestCircumference"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.chestCircumference">
    <xs:attribute name="unit" use="required" form="qualified"/>
  </xs:attributeGroup>
  
  <xs:element name="headCircumference">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="mmlFcl:attlist.headCircumference"/>
    </xs:complexType>
  </xs:element>
  
  <xs:attributeGroup name="attlist.headCircumference">
    <xs:attribute name="unit" use="required" form="qualified"/>
  </xs:attributeGroup>
  
  <xs:element name="vaccination">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="mmlFcl:vaccinationItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="vaccinationItem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mmlFcl:vaccine"/>
        <xs:element ref="mmlFcl:injected"/>
        <xs:element minOccurs="0" ref="mmlFcl:age"/>
        <xs:element minOccurs="0" ref="mmlFcl:memo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="vaccine" type="xs:string"/>
  
  <xs:element name="injected" type="xs:string"/>
  
  <xs:element name="pastHistory">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="mmlFcl:freeNotes"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlFcl:pastHistoryItem"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="pastHistoryItem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mmlFcl:timeExpression"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="mmlFcl:eventExpression"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="timeExpression" type="xs:string"/>
  
  <xs:element name="eventExpression" type="xs:string"/>
  
  <xs:element name="chiefComplaints" type="xs:string"/>
  
  <xs:element name="presentIllnessNotes" type="xs:string"/>
  
  <xs:element name="freeNotes" type="xs:string"/>
  
</xs:schema>

=== skoba/mml/schema/draft/sample/mmlfcl_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<mmlFcl:FirstClinicModule
  xmlns:mmlFcl="http://www.medxml.net/MML/v4/ContentModule/FirstClinic/1.0"
  xmlns:mmlRd="http://www.medxml.net/MML/v4/ContentModule/RegisteredDiagnosis/1.0"
  xmlns:mmlFc="http://www.medxml.net/MML/v4/SharedComponent/Facility/1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.medxml.net/MML/v4/ContentModule/FirstClinic/1.0 ../firstclinic.xsd"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <mmlFcl:familyHistory>
    <mmlFcl:familyHistoryItem>
      <mmlFcl:relation>motherInLaw</mmlFcl:relation>
      <mmlRd:RegisteredDiagnosisModule>
        <mmlRd:diagnosis mmlRd:code="C169-.007" mmlRd:system="ICD10">gastric cancer</mmlRd:diagnosis>
        <mmlRd:endDate>1989-08-25</mmlRd:endDate>
        <mmlRd:outcome>died</mmlRd:outcome>
      </mmlRd:RegisteredDiagnosisModule>
      <mmlFcl:age>P40Y</mmlFcl:age>
    </mmlFcl:familyHistoryItem>
  </mmlFcl:familyHistory>
  <mmlFcl:childhood>
    <mmlFcl:birthInfo>
      <mmlFcl:deliveryWeeks>P40W</mmlFcl:deliveryWeeks>
      <mmlFcl:deliveryMethod>cesarean section</mmlFcl:deliveryMethod>
      <mmlFcl:bodyWeight mmlFcl:unit="g">3270</mmlFcl:bodyWeight>
      <mmlFcl:bodyHeight mmlFcl:unit="cm">50</mmlFcl:bodyHeight>
    </mmlFcl:birthInfo>
  </mmlFcl:childhood>
  <mmlFcl:vaccination>
    <mmlFcl:vaccinationItem>
      <mmlFcl:vaccine>polio</mmlFcl:vaccine>
      <mmlFcl:injected>true</mmlFcl:injected>
      <mmlFcl:age>P6M</mmlFcl:age>
      <mmlFcl:memo>first administration</mmlFcl:memo>
    </mmlFcl:vaccinationItem>
    <mmlFcl:vaccinationItem>
      <mmlFcl:vaccine>polio</mmlFcl:vaccine>
      <mmlFcl:injected>true</mmlFcl:injected>
      <mmlFcl:age>P1Y6M</mmlFcl:age>
      <mmlFcl:memo>second administration</mmlFcl:memo>
    </mmlFcl:vaccinationItem>
  </mmlFcl:vaccination>
  <mmlFcl:pastHistory>
    <mmlFcl:pastHistoryItem>
      <mmlFcl:timeExpression>6 years old</mmlFcl:timeExpression>
      <mmlFcl:eventExpression>appendectomy</mmlFcl:eventExpression>
    </mmlFcl:pastHistoryItem>
    <mmlFcl:pastHistoryItem>
      <mmlFcl:timeExpression>5 years ago (1994)</mmlFcl:timeExpression>
      <mmlFcl:eventExpression>hypertension</mmlFcl:eventExpression>
    </mmlFcl:pastHistoryItem>
  </mmlFcl:pastHistory>
  <mmlFcl:chiefComplaints>頭痛</mmlFcl:chiefComplaints>
  <mmlFcl:presentIllnessNotes>2週間前より一日に数回側頭部から頭頂部にかけてのずきずきする痛みがあり。</mmlFcl:presentIllnessNotes>
</mmlFcl:FirstClinicModule>
